schema_version: 1

context:
  build_number: 1
  name: sbcl
  version: "2.6.9"
  sh: ${{ ".sh" if unix else ".bat" }}

package:
  name: sbcl
  version: ${{ version }}

source:
  - url: http://prdownloads.sourceforge.net/sbcl/sbcl-${{ version }}-source.tar.bz2
    sha256: c6fd1d735570eb4ff34caf9609988ca77ed0bd12b55d09a4fed075be890da513
    target_directory: sbcl-source
    patches:
      - if: linux
        then:
          - patches/linux/0001-x86_64-aarch64-ppc64le-zstd.patch
          - patches/linux/0002-target-runtime-launcher.patch
      - if: target_platform == "linux-riscv64"
        then:
          - patches/linux/0003-target-runtime-launcher-contrib.patch
      - if: osx
        then:
          - patches/osx/0001-update-rpath-zstd.patch
      - if: not unix
        then:
          - patches/win/0001-rewrite-long-xargs.patch
          - patches/win/0002-add-link-zstd.patch
          - patches/win/0003-add-build-dll.patch
          - patches/win/0004-improve-sbcl_home-test.patch

build:
  number: ${{ build_number }}

requirements:
  build:
    - if: unix
      then:
        - ${{ compiler('c') }}
      else:
        - ${{ compiler('m2w64_c') }}
        - m2-coreutils
        - m2-findutils
        - m2-grep
    - ${{ stdlib('c') }}
    - make
    - if: riscv64 or ppc64le
      then:
        - qemu-execve-${{ target_platform | replace("linux-", "") }}
    - sbcl
  host:
    # zstd not yet available
    - if: not (osx and arm64) and not riscv64
      then:
        - zstd

tests:
  - package_contents:
      strict: true
      bin:
        - sbcl
      lib:
        - if: unix
          then:
            - sbcl
      files:
        - etc/conda/activate.d/sbcl-activate${{ sh }}
        - etc/conda/deactivate.d/sbcl-deactivate${{ sh }}
        - if: osx
          then:
            - lib/libsbcl.so
        - if: not unix
          then:
            - bin/libsbcl.dll
            - lib/libsbcl.lib
        - lib/sbcl/contrib/{asdf,uiop}.fasl
        - lib/sbcl/contrib/sb-{aclrepl,bsd-sockets,capstone,cltl2,concurrency,cover}.{asd,fasl}
        - lib/sbcl/contrib/sb-{executable,gmp,grovel,introspect,manual,md5,mpfr}.{asd,fasl}
        - lib/sbcl/contrib/sb-{posix,queue,rotate-byte,rt,simd,simple-streams,sprof}.{asd,fasl}
        - lib/sbcl/sbcl.core
        - lib/sbcl/sbcl.mk
        - lib/sbcl/sbclrc
        - lib/sbcl/sbclrc.d/00-README.lisp
        - share/doc/sbcl/{BUGS,COPYING,CREDITS,NEWS}
        - share/man/man1/sbcl.1
        - if: linux
          then:
            - lib/sbcl/contrib/sb-perf.{asd,fasl}
        - if: x86_64
          then:
            - lib/sbcl/contrib/sb-simd.{asd,fasl}

  - script:
      - sbcl --version
      - sbcl --help
      - sbcl --noinform --disable-debugger --eval "(print (require :asdf))" --disable-debugger --eval "(quit)"
    requirements:
      run:
        - if: linux and not (target_platform == "linux-ppc64le" or target_platform == "linux-riscv64")
          then:
            - strace

about:
  homepage: http://www.sbcl.org
  license: BSD-2-Clause AND MIT
  summary: Steel Bank Common Lisp (SBCL) is a high performance Common Lisp compiler
  description: |
    Steel Bank Common Lisp (SBCL) is a high performance Common Lisp compiler.
    It is open source / free software, with a permissive license. In addition to the
    compiler and runtime system for ANSI Common Lisp, it provides an interactive
    environment including a debugger, a statistical profiler, a code coverage tool,
    and many other extensions.
  documentation: http://www.sbcl.org/manual/index.html
  license_file:
    - COPYING
    - CREDITS

extra:
  recipe-maintainers:
    - MementoRC
    - wolfv
    - Tobias-Fischer
